version: "3"
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db
  frontend-server:
    image: git.simplendi.com:5443/firmq/frontend-server:latest
    container_name: frontend-server
    ports:
      - "8080:8080"
    entrypoint: /usr/lib/bin/frontend-server -v=10
    links:
      - mongodb
    environment:
      - SIMPLENDI_NEXMO_API_KEY=""
      - SIMPLENDI_NEXMO_SECRET_KEY=""

volumes:
  data-volume:
