// Code generated by protoc-gen-go.
// source: proto/common/common.proto
// DO NOT EDIT!

/*
Package common is a generated protocol buffer package.

It is generated from these files:
	proto/common/common.proto

It has these top-level messages:
	IDRequest
	MetaResponse
	CommonResponse
	IDResponse
	Address
*/
package common

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IDRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *IDRequest) Reset()                    { *m = IDRequest{} }
func (m *IDRequest) String() string            { return proto.CompactTextString(m) }
func (*IDRequest) ProtoMessage()               {}
func (*IDRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *IDRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MetaResponse struct {
	Ok         bool   `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Error      string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	StatusCode int32  `protobuf:"varint,3,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
}

func (m *MetaResponse) Reset()                    { *m = MetaResponse{} }
func (m *MetaResponse) String() string            { return proto.CompactTextString(m) }
func (*MetaResponse) ProtoMessage()               {}
func (*MetaResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MetaResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *MetaResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *MetaResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

type CommonResponse struct {
	Meta *MetaResponse `protobuf:"bytes,1,opt,name=meta" json:"meta,omitempty"`
}

func (m *CommonResponse) Reset()                    { *m = CommonResponse{} }
func (m *CommonResponse) String() string            { return proto.CompactTextString(m) }
func (*CommonResponse) ProtoMessage()               {}
func (*CommonResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CommonResponse) GetMeta() *MetaResponse {
	if m != nil {
		return m.Meta
	}
	return nil
}

type IDResponse struct {
	Meta *MetaResponse `protobuf:"bytes,1,opt,name=meta" json:"meta,omitempty"`
	Id   string        `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *IDResponse) Reset()                    { *m = IDResponse{} }
func (m *IDResponse) String() string            { return proto.CompactTextString(m) }
func (*IDResponse) ProtoMessage()               {}
func (*IDResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *IDResponse) GetMeta() *MetaResponse {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *IDResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Address struct {
	AddressLine_1 string `protobuf:"bytes,1,opt,name=address_line_1,json=addressLine1" json:"address_line_1,omitempty"`
	AddressLine_2 string `protobuf:"bytes,2,opt,name=address_line_2,json=addressLine2" json:"address_line_2,omitempty"`
	City          string `protobuf:"bytes,3,opt,name=city" json:"city,omitempty"`
	Region        string `protobuf:"bytes,4,opt,name=region" json:"region,omitempty"`
	PostalCode    string `protobuf:"bytes,5,opt,name=postal_code,json=postalCode" json:"postal_code,omitempty"`
	Country       string `protobuf:"bytes,6,opt,name=country" json:"country,omitempty"`
}

func (m *Address) Reset()                    { *m = Address{} }
func (m *Address) String() string            { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()               {}
func (*Address) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Address) GetAddressLine_1() string {
	if m != nil {
		return m.AddressLine_1
	}
	return ""
}

func (m *Address) GetAddressLine_2() string {
	if m != nil {
		return m.AddressLine_2
	}
	return ""
}

func (m *Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Address) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *Address) GetPostalCode() string {
	if m != nil {
		return m.PostalCode
	}
	return ""
}

func (m *Address) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func init() {
	proto.RegisterType((*IDRequest)(nil), "grpc.gateway.common.IDRequest")
	proto.RegisterType((*MetaResponse)(nil), "grpc.gateway.common.MetaResponse")
	proto.RegisterType((*CommonResponse)(nil), "grpc.gateway.common.CommonResponse")
	proto.RegisterType((*IDResponse)(nil), "grpc.gateway.common.IDResponse")
	proto.RegisterType((*Address)(nil), "grpc.gateway.common.Address")
}

func init() { proto.RegisterFile("proto/common/common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x51, 0x4d, 0x4b, 0x03, 0x31,
	0x10, 0x65, 0xd7, 0x76, 0xdb, 0x4e, 0x4b, 0x0f, 0x51, 0x64, 0xfd, 0x00, 0xeb, 0xe2, 0xa1, 0xa7,
	0x2d, 0xad, 0xf8, 0x03, 0xb4, 0x82, 0x08, 0x7a, 0x89, 0x78, 0xf1, 0x52, 0xe2, 0xee, 0xb0, 0x84,
	0xb6, 0x99, 0x35, 0x49, 0x91, 0xfe, 0x37, 0x7f, 0x9c, 0x6c, 0x12, 0x4b, 0x41, 0x6f, 0x9e, 0x32,
	0xf3, 0xde, 0xcc, 0x63, 0xde, 0x0b, 0x9c, 0xd4, 0x9a, 0x2c, 0x4d, 0x0a, 0x5a, 0xaf, 0x49, 0x85,
	0x27, 0x77, 0x18, 0x3b, 0xac, 0x74, 0x5d, 0xe4, 0x95, 0xb0, 0xf8, 0x29, 0xb6, 0xb9, 0xa7, 0x4e,
	0xcf, 0x2b, 0xa2, 0x6a, 0x85, 0x13, 0x51, 0xcb, 0x89, 0x50, 0x8a, 0xac, 0xb0, 0x92, 0x94, 0xf1,
	0x2b, 0xd9, 0x19, 0xf4, 0x1e, 0xef, 0x39, 0x7e, 0x6c, 0xd0, 0x58, 0x36, 0x84, 0x58, 0x96, 0x69,
	0x34, 0x8a, 0xc6, 0x3d, 0x1e, 0xcb, 0x32, 0x7b, 0x85, 0xc1, 0x33, 0x5a, 0xc1, 0xd1, 0xd4, 0xa4,
	0x0c, 0x36, 0x3c, 0x2d, 0x1d, 0xdf, 0xe5, 0x31, 0x2d, 0xd9, 0x11, 0xb4, 0x51, 0x6b, 0xd2, 0x69,
	0xec, 0x56, 0x7c, 0xc3, 0x2e, 0xa0, 0x6f, 0xac, 0xb0, 0x1b, 0xb3, 0x28, 0xa8, 0xc4, 0xf4, 0x60,
	0x14, 0x8d, 0xdb, 0x1c, 0x3c, 0x34, 0xa7, 0x12, 0xb3, 0x07, 0x18, 0xce, 0xdd, 0x6d, 0x3b, 0xe1,
	0x1b, 0x68, 0xad, 0xd1, 0x0a, 0x27, 0xdd, 0x9f, 0x5d, 0xe6, 0x7f, 0xf8, 0xc8, 0xf7, 0x2f, 0xe1,
	0x6e, 0x3c, 0x7b, 0x01, 0x68, 0x8e, 0xff, 0x97, 0x48, 0x30, 0x1d, 0xef, 0x4c, 0x7f, 0x45, 0xd0,
	0xb9, 0x2d, 0x4b, 0x8d, 0xc6, 0xb0, 0x2b, 0x18, 0x0a, 0x5f, 0x2e, 0x56, 0x52, 0xe1, 0x62, 0x1a,
	0xc2, 0x19, 0x04, 0xf4, 0x49, 0x2a, 0x9c, 0xfe, 0x9a, 0x9a, 0x05, 0xb5, 0xfd, 0xa9, 0x19, 0x63,
	0xd0, 0x2a, 0xa4, 0xdd, 0xba, 0x3c, 0x7a, 0xdc, 0xd5, 0xec, 0x18, 0x12, 0x8d, 0x95, 0x24, 0x95,
	0xb6, 0x1c, 0x1a, 0xba, 0x26, 0xc2, 0x9a, 0x8c, 0x15, 0x2b, 0x1f, 0x61, 0xdb, 0x91, 0xe0, 0xa1,
	0x26, 0x42, 0x96, 0x42, 0xa7, 0xa0, 0x8d, 0xb2, 0x7a, 0x9b, 0x26, 0x8e, 0xfc, 0x69, 0xef, 0xba,
	0x6f, 0x89, 0xf7, 0xfa, 0x9e, 0xb8, 0x1f, 0xbe, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x78, 0x37,
	0xe4, 0xa5, 0x31, 0x02, 0x00, 0x00,
}
